# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy-release-test:
    if: github.ref != 'main'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    needs: build 

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      env:
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TEST_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: |
          dotnet nuget push ./DependencyGraph.Core/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
          dotnet nuget push ./DependencyGraph.App/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - name: Github prerelease
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      if:  env.GITHUB_TOKEN != ''
      run: |
          gh release create ${{env.CURRENT_VERSION}} **/*.nupkg --prerelease --generate-notes